---
title: "Homework04"
author: "Mark D. Mullinger"
date: "2023-02-08"
output: html_document
---

This assignment covers how to work with vectors in R, including some simple functions.

1.
Question one involved substituting values into the following given equations
```
z <- 1.1^2.2^3.3
print(z)
[1] 3.61714
z <- (1.1^2.2)^3.3
print(z)
[1] 1.997611
z <- 3*1.1^3+2*1.1^2+1
print(z)
[1] 7.413
```

2.

  a. 
  To create this vector, first I created a sequence from 1 to 8, and then from 7 to 1, and put them together to create the final string.
```
z <- seq(from=1,to=8, by=1)
y <- seq(from=7, to=1, by=-1)
v <- c(z,y)
print(v)
 [1] 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1
```

  b.
  To make this vector, first I created a sequence from 1 to 5. Next I used the repeat function to repeat each number by itself number of times.
```
z <- seq(from=1, to=5, by=1)
v <- rep(z, times=z)
print(v)
 [1] 1 2 2 3 3 3 4 4 4 4 5 5 5 5 5
```

  c.
  To make this vector, the above operation was inverted by changing the "by" input to a negative. 
```
z <- seq(from=1, to=5, by=1)
v <- rep(seq(from=5, to=1, by=-1), times=z)
print(v)
 [1] 5 4 4 3 3 3 2 2 2 2 1 1 1 1 1
```

3.
To convert coordinates from cartesian to polar, first I created the cartesian coordinates randomly using runif(). Next, I solved for each component of a polar vector seperately as r and theta. Finally I put those two together to form our polar coordinates. 
```
cartvec <- runif(2, min=1, max=14)
print(cartvec)
[1] 4.32448 5.08981
r <- sqrt((cartvec[1])^2+(cartvec[2]^2))
print(r)
[1] 6.67887
theta <- atan(cartgvec[2]/cartvec[1])
print(theta)
[1] 0.8665143
polarvec <- c(r,theta)
print(polarvec)
[1] 6.6788697 0.8665143
```

4. 
starting queue: ```queue <- c("sheep", "fox", "owl", "ant")```
a. the serpent gets in line ```queue <- c(queue, "serpent")```
b. the sheep enters the ark ```queue <- queue[! queue %in% "sheep"]```
c. the donkey cuts in front of everyone ```queue <- append(queue, "donkey", after=0)```
d. the serpent leaves ```queue <- queue[! queue %in% "serpent"]```
e. the owl leaves ```queue <- queue[! queue %in% "owl"]```
f. the aphid joins and ant lets them cut in front ```queue <- append(queue, "aphid", after=2)```
g. where is the aphid in line? ```match("aphid", queue)```

5.
First, I created a vector of all the integers 1 - 100. Next, to find those not divisible by 2, 3, or 7 I used the which() function, setting it up to find the components of x, which when divided by 2, 3, or 7 equal 0. Finally, I used the not(!) to remove those from the vector.
```
x <- seq(1:100)
v <- which(! x%%2== 0 & ! x%%3== 0 & ! x%%7==0)
```
