---
title: "BIO381: computational biology"
author: "Mark D. Mullinger"
date: "2023-01-25"
output: 
  html_document: 
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Welcome!

You have navigated to a web-based portfolio of work I've completed as a part of a computational biology class at the University of Vermont. 

## [Homework02](Homework02.html)

This assignment proves I can build a webpage and contains a fun fact about myself.

## [Homework03](Homework03.html)

In this assignment we explored how to use regular expressions in a plain text editor to make quick edits to large data sets. These expressions are used mostly in cleaning and preparing data files to be analyzed.

## [Homework04](Homework04.html)

This week's assignment involved some practice manipulating vectors in R.

## [Homework05](Homework05.html)

Homework number 5 was all about matrices, lists, and data frames (and how to manupulate them).

## [Homework06](Homework06.html)

Homework six we took a look at the ```dplyr``` package and how to manipulate data frames with it.

## [Homework07](Homework07.html)

Homework seven involved simulating data and fitting those data with distribution curved.

## [Homework08](Homework08.html)

This week's work involved constructing simulated data sets to find the statistical limits of hypotheses. 

## [Homework10](Homework10.html)

## [Homework12](Homework12.html)